# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

jobs:
  include:
    - r: 3.2
    - r: oldrel
    - r: release
    - r: devel
    - os: osx

matrix:
  fast_finish: true